CREATE TABLE gold_dim_products (
    PRODUCT_SK INTEGER AUTOINCREMENT, 
	PRODUCT_ID NUMBER(38,0),
	PRODUCT_NAME VARCHAR(16777216),
	SUPPLIER_ID NUMBER(38,0),
	CATEGORY_ID NUMBER(38,0),
	QUANTITY_PER_UNIT VARCHAR(16777216),
	UNIT_PRICE FLOAT,
	UNITS_IN_STOCK NUMBER(38,0),
	UNITS_ON_ORDER NUMBER(38,0),
	REORDER_LEVEL NUMBER(38,0),
	DISCONTINUED NUMBER(38,0),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
