CREATE TABLE IF NOT EXISTS GOLD_DIM_CUSTOMERS (

    CUSTOMER_SK INTEGER AUTOINCREMENT, 
	CUSTOMER_ID VARCHAR(20),
	COMPANY_NAME VARCHAR(100),
	CONTACT_NAME VARCHAR(200),
	CONTACT_TITLE VARCHAR(100),
	ADDRESS VARCHAR(300),
	CITY VARCHAR(100),
	POSTAL_CODE VARCHAR(100),
	COUNTRY VARCHAR(100),
	PHONE VARCHAR(100),
	FAX VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);