name: Deploy Snowflake View

on:
  workflow_dispatch:
    inputs:
      target_schema:
        description: 'Schema de destino (ex: public, qa, prd)'
        required: true
        default: 'public'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libaio1 libncurses5

      - name: Instalar SnowSQL
        run: |
          set -x
          wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.4.1-linux_x86_64.bash
          SNOWSQL_DEST=/home/runner/.snowsql bash snowsql-1.4.1-linux_x86_64.bash -b
          echo 'export PATH=$PATH:/home/runner/.snowsql/bin' >> $GITHUB_ENV

      - name: Executar script no Snowflake
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
        run: |
          snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PWD \
            -D TARGET_SCHEMA=${{ github.event.inputs.target_schema }} \
            -f poc-snow/sql/views/stg_orders.sql 
