name: Test Snowflake View

on:
  workflow_dispatch:
    inputs:
      target_schema:
        description: 'Schema de destino (ex: public, qa, prd)'
        required: true
        default: 'public'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Baixar instalador do SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.27-linux_x86_64.bash

      - name: Instalar SnowSQL
        run: |
          SNOWSQL_DEST=$HOME/.snowsql
          bash snowsql-1.2.27-linux_x86_64.bash -y
          echo "$HOME/.snowsql/bin" >> $GITHUB_PATH

      - name: Verificar instalação do SnowSQL
        run: snowsql -v

      - name: Executar script no Snowflake
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
        run: |
          snowsql \
            -a $SNOWSQL_ACCOUNT \
            -u $SNOWSQL_USER \
            -p $SNOWSQL_PWD \
            -D TARGET_SCHEMA=${{ github.event.inputs.target_schema }} \
            -f poc-snow/sql/views/stg_orders.sql
